import type { ReaderDto, ReaderListItemDto } from '../api/readers.dto';

export const READER_DTO: ReaderDto = {
  id: 'reader-1',
  photoFileId: 'photo-1',
  cardNumber: '0000001',
  category: 1,
  lastName: 'Karimova',
  firstName: 'Gulnoza',
  middleName: 'Anvar qizi',
  birthDate: '2004-05-17',
  gender: 1,
  citizenship: 0,
  phone: '+998905551234',
  source: 1,
  issuedOn: '2026-09-26',
  expiresOn: '2028-09-26',
  isExpired: false,
  printCount: 0,
  lastPrintedAt: null,
  createdAt: '2026-09-26T17:49:55Z',
  createdByName: 'Resepshn Xodimi',
  updatedAt: null,
};

export const READER_LIST_ITEM_DTO: ReaderListItemDto = {
  id: READER_DTO.id,
  photoFileId: READER_DTO.photoFileId,
  cardNumber: READER_DTO.cardNumber,
  category: READER_DTO.category,
  lastName: READER_DTO.lastName,
  firstName: READER_DTO.firstName,
  middleName: READER_DTO.middleName,
  birthDate: READER_DTO.birthDate,
  gender: READER_DTO.gender,
  citizenship: READER_DTO.citizenship,
  phone: READER_DTO.phone,
  source: READER_DTO.source,
  issuedOn: READER_DTO.issuedOn,
  expiresOn: READER_DTO.expiresOn,
  isExpired: false,
  printCount: 0,
  createdAt: READER_DTO.createdAt,
};
